version: '3.8'

services:
  go-eigentrust-8081:
    build: .
    image: go-eigentrust:latest
    container_name: go-eigentrust-8081
    ports:
      - "8081:80"
    command: ["/app/build/main", "serve"]

  go-eigentrust-9081:
    build: .
    image: go-eigentrust:latest
    container_name: go-eigentrust-9081
    ports:
      - "9081:80"
    command: ["/app/build/main", "serve"]
