services:
  go-eigentrust-8081:
    build: 
      dockerfile: fileuri.Dockerfile
    image: go-eigentrust:latest
    container_name: go-eigentrust-8081
    volumes:
      - ${GO_EIGENTRUST_BIND_SRC}:${GO_EIGENTRUST_BIND_TARGET}:z
    ports:
      - "8081:80"

  go-eigentrust-9081:
    build: 
      dockerfile: fileuri.Dockerfile
    image: go-eigentrust:latest
    container_name: go-eigentrust-9081
    volumes:
      - ${GO_EIGENTRUST_BIND_SRC}:${GO_EIGENTRUST_BIND_TARGET}:z
    ports:
      - "9081:80"