// Code generated by ogen, DO NOT EDIT.
package ogen

type ComputeRes interface {
	computeRes()
}

type ComputeWithStatsRes interface {
	computeWithStatsRes()
}

type DeleteLocalTrustRes interface {
	deleteLocalTrustRes()
}

type GetLocalTrustRes interface {
	getLocalTrustRes()
}

type GetStatusRes interface {
	getStatusRes()
}

type HeadLocalTrustRes interface {
	headLocalTrustRes()
}

type UpdateLocalTrustRes interface {
	updateLocalTrustRes()
}
