// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	ComputeOperation          OperationName = "Compute"
	ComputeWithStatsOperation OperationName = "ComputeWithStats"
	DeleteLocalTrustOperation OperationName = "DeleteLocalTrust"
	GetLocalTrustOperation    OperationName = "GetLocalTrust"
	GetStatusOperation        OperationName = "GetStatus"
	HeadLocalTrustOperation   OperationName = "HeadLocalTrust"
	UpdateLocalTrustOperation OperationName = "UpdateLocalTrust"
)
