// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Compute implements compute operation.
//
// Compute EigenTrust scores using the given inputs.
// A compute request takes four inputs:
// * Local trust matrix, in sparse form
// * Pre-trust vector, in sparse form
// * Pre-trust strength, a floating-point number between 0 and 1
// * Error threshold, a floating-point number between 0 and 1
// The local trust matrix is required; all others are optional.
//
// POST /compute
func (UnimplementedHandler) Compute(ctx context.Context, req *ComputeRequestBody) (r ComputeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ComputeWithStats implements computeWithStats operation.
//
// Compute EigenTrust scores using the given inputs.
// See /compute for details.
// The only difference is that not just the EigenTrust scores but also
// statistics and rankings are returned.
//
// POST /compute-with-stats
func (UnimplementedHandler) ComputeWithStats(ctx context.Context, req *ComputeRequestBody) (r ComputeWithStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteLocalTrust implements deleteLocalTrust operation.
//
// Delete local trust.
//
// DELETE /local-trust/{id}
func (UnimplementedHandler) DeleteLocalTrust(ctx context.Context, params DeleteLocalTrustParams) (r DeleteLocalTrustRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLocalTrust implements getLocalTrust operation.
//
// Return the given locally stored local trust as an inline ref.
//
// GET /local-trust/{id}
func (UnimplementedHandler) GetLocalTrust(ctx context.Context, params GetLocalTrustParams) (r GetLocalTrustRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatus implements getStatus operation.
//
// Get the health check status.
//
// GET /status
func (UnimplementedHandler) GetStatus(ctx context.Context) (r GetStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HeadLocalTrust implements headLocalTrust operation.
//
// Return 204 if the given local trust exists, 404 otherwise.
//
// HEAD /local-trust/{id}
func (UnimplementedHandler) HeadLocalTrust(ctx context.Context, params HeadLocalTrustParams) (r HeadLocalTrustRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateLocalTrust implements updateLocalTrust operation.
//
// Load and locally cache the local trust
// from the given local trust reference.
//
// PUT /local-trust/{id}
func (UnimplementedHandler) UpdateLocalTrust(ctx context.Context, req *TrustRef, params UpdateLocalTrustParams) (r UpdateLocalTrustRes, _ error) {
	return r, ht.ErrNotImplemented
}
