// Package basic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package basic

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for InlineLocalTrustScheme.
const (
	InlineLocalTrustSchemeInline InlineLocalTrustScheme = "inline"
)

// Defines values for InlineTrustVectorScheme.
const (
	InlineTrustVectorSchemeInline InlineTrustVectorScheme = "inline"
)

// Defines values for LocalTrustRefScheme.
const (
	LocalTrustRefSchemeInline        LocalTrustRefScheme = "inline"
	LocalTrustRefSchemeObjectstorage LocalTrustRefScheme = "objectstorage"
	LocalTrustRefSchemeStored        LocalTrustRefScheme = "stored"
)

// Defines values for ObjectStorageLocalTrustScheme.
const (
	ObjectStorageLocalTrustSchemeObjectstorage ObjectStorageLocalTrustScheme = "objectstorage"
)

// Defines values for ObjectStorageTrustVectorScheme.
const (
	ObjectStorageTrustVectorSchemeObjectstorage ObjectStorageTrustVectorScheme = "objectstorage"
)

// Defines values for StoredLocalTrustScheme.
const (
	Stored StoredLocalTrustScheme = "stored"
)

// Defines values for TrustVectorRefScheme.
const (
	TrustVectorRefSchemeInline        TrustVectorRefScheme = "inline"
	TrustVectorRefSchemeObjectstorage TrustVectorRefScheme = "objectstorage"
	TrustVectorRefSchemeStored        TrustVectorRefScheme = "stored"
)

// FlatTailStats Flat-tail algorithm stats and peer ranking.
type FlatTailStats struct {
	// DeltaNorm The d value as of the head of the last flat-tail.
	// This can be used to fine-tune epsilon
	// even when not using flat-tail algorithm.
	DeltaNorm float64 `json:"deltaNorm"`

	// Length The flat-tail length (say, L, then
	// the last L+1 iterations had the same ranking).
	// This is the number of iterations that could be saved
	// by using flat-tail algorithm
	// (passing flatTail equal to the threshold stat below)
	// while achieving the same result.
	Length int `json:"length"`

	// Ranking The sorted ranking of peer indices.
	// Peers not found here have zero global trust.
	Ranking []int `json:"ranking"`

	// Threshold The suggested minimum threshold parameter (flatTail).
	// It is determined from false flat tails observed.
	// Example: If a ranking pattern ABCDDEEEEFFFFFFFFFF was observed
	// (each letter is a distinct ranking) before epsilon was reached,
	// both DD and EEEE are false flat tails
	// of length 1 and 3 respectively.
	// In this case, Threshold=4 is suggested in order to ignore
	// these false flat tails.
	Threshold int `json:"threshold"`
}

// InlineLocalTrust Refers to a local trust matrix "inline".
//
// Instead of pointing (referencing) to an externally stored local trust,
// it carries the contents of the local trust matrix
// within the reference object itself.
type InlineLocalTrust struct {
	// Entries Contains the non-zero entries in the local trust matrix.
	//
	// Truster/trustee pairs missing here are assigned zero direct trust,
	// i.e. no trust relationship.
	Entries []InlineLocalTrustEntry `json:"entries"`

	// Scheme A fixed string `"inline"`.
	Scheme InlineLocalTrustScheme `json:"scheme"`

	// Size Denotes the number of peers in the local trust,
	// i.e. its square dimension.
	Size int `json:"size"`
}

// InlineLocalTrustScheme A fixed string `"inline"`.
type InlineLocalTrustScheme string

// InlineLocalTrustEntry Represents an entry in the local trust matrix.
//
// Denotes that one peer (`i`) places a direct trust in another peer (`j`)
// by a specific amount (`v`).
type InlineLocalTrustEntry struct {
	// I Denotes the trusting peer.
	//
	// It is a zero-based index,
	// and must be less than the size (dimension)
	// of the enclosing local trust matrix.
	I int `json:"i"`

	// J Denotes the trusted peer.
	//
	// It is a zero-based index,
	// and must be less than the size (dimension)
	// of the enclosing local trust matrix.
	J int `json:"j"`

	// V Represents the (positive) amount of trust
	// placed by peer `i` in peer `j`.
	V float64 `json:"v"`
}

// InlineTrustVector Refers to a trust vector "inline".
//
// Instead of pointing (referencing) to an externally stored trust vector,
// it carries the contents of the trust vector
// within the reference object itself.
type InlineTrustVector struct {
	// Entries Contains the non-zero entries in the trust vector.
	//
	// Peers missing here are assigned zero amount of trust.
	Entries []InlineTrustVectorEntry `json:"entries"`

	// Scheme A fixed string `"inline"` to denote an inline reference.
	Scheme InlineTrustVectorScheme `json:"scheme"`

	// Size Denotes the number of peers in the trust vector, i.e. its length.
	Size int `json:"size"`
}

// InlineTrustVectorScheme A fixed string `"inline"` to denote an inline reference.
type InlineTrustVectorScheme string

// InlineTrustVectorEntry Represents an entry in the local trust matrix.
//
// Denotes that a trust is placed in a peer (`i`)
// by a specific amount (`v`).
type InlineTrustVectorEntry struct {
	// I Denotes the peer.
	//
	// It is a zero-based index,
	// and must be less than the length of the enclosing trust vector.
	I int `json:"i"`

	// V Represents the (positive) amount of trust placed in peer `i`.
	V float64 `json:"v"`
}

// LocalTrustId Denotes a local trust collection.
type LocalTrustId = string

// LocalTrustRef defines model for LocalTrustRef.
type LocalTrustRef struct {
	// Scheme Local trust reference scheme, akin to URI scheme.
	Scheme LocalTrustRefScheme `json:"scheme"`
	union  json.RawMessage
}

// LocalTrustRefScheme Local trust reference scheme, akin to URI scheme.
type LocalTrustRefScheme string

// ObjectStorageLocalTrust Refers to a local trust matrix in a remote object storage service.
type ObjectStorageLocalTrust struct {
	// Scheme A fixed string `"objectstorage"`.
	Scheme ObjectStorageLocalTrustScheme `json:"scheme"`

	// Url URL of the trust matrix file.
	//
	// It must refer to a CSV file, with three columns `i`, `j`, and `v`.
	// Currently the `s3://` URL scheme (AWS S3) is supported.
	Url string `json:"url"`
}

// ObjectStorageLocalTrustScheme A fixed string `"objectstorage"`.
type ObjectStorageLocalTrustScheme string

// ObjectStorageTrustVector Refers to a trust vector in a remote object storage service.
type ObjectStorageTrustVector struct {
	// Scheme A fixed string `"objectstorage"`.
	Scheme ObjectStorageTrustVectorScheme `json:"scheme"`

	// Url URL of the trust vector file.
	//
	// It must refer to a CSV file, with two columns `i` and `v`.
	// Currently the `s3://` URL scheme (AWS S3) is supported.
	Url string `json:"url"`
}

// ObjectStorageTrustVectorScheme A fixed string `"objectstorage"`.
type ObjectStorageTrustVectorScheme string

// StoredLocalTrust Refers to a local trust stored on the server.
//
// Stored local trust is identified with its ID string.
type StoredLocalTrust struct {
	// Id Denotes a local trust collection.
	Id LocalTrustId `json:"id"`

	// Scheme A fixed string `"stored"`.
	Scheme StoredLocalTrustScheme `json:"scheme"`
}

// StoredLocalTrustScheme A fixed string `"stored"`.
type StoredLocalTrustScheme string

// TrustVectorRef defines model for TrustVectorRef.
type TrustVectorRef struct {
	// Scheme Trust vector reference scheme, akin to URI scheme.
	Scheme TrustVectorRefScheme `json:"scheme"`
	union  json.RawMessage
}

// TrustVectorRefScheme Trust vector reference scheme, akin to URI scheme.
type TrustVectorRefScheme string

// LocalTrustIdParam Denotes a local trust collection.
type LocalTrustIdParam = LocalTrustId

// ComputeWithStatsResponseOK defines model for ComputeWithStatsResponseOK.
type ComputeWithStatsResponseOK struct {
	// EigenTrust Refers to a trust vector.
	EigenTrust TrustVectorRef `json:"eigenTrust"`

	// FlatTailStats Flat-tail algorithm stats and peer ranking.
	FlatTailStats FlatTailStats `json:"flatTailStats"`
}

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest struct {
	// Message Describes the error in a human-readable message.
	//
	// It may be empty.
	Message string `json:"message"`
}

// ComputeRequestBody defines model for ComputeRequestBody.
type ComputeRequestBody struct {
	Alpha   *float64 `json:"alpha,omitempty"`
	Epsilon *float64 `json:"epsilon,omitempty"`

	// FlatTail The length of the flat tail
	// (ranking unchanged from previous iteration)
	// that must be seen before terminating the recursion.
	// 0 means a flat tail need not be seen,
	// and the recursion is terminated solely based upon epsilon.
	FlatTail *int `json:"flatTail,omitempty"`

	// InitialTrust Refers to a trust vector.
	InitialTrust *TrustVectorRef `json:"initialTrust,omitempty"`

	// LocalTrust refers to a local trust.
	LocalTrust LocalTrustRef `json:"localTrust"`

	// MaxIterations The maximum number of iterations after which to stop
	// even if other termination criteria are not met.
	// 0 means no limit.
	MaxIterations *int `json:"maxIterations,omitempty"`

	// NumLeaders The number of top-ranking peers to consider
	// for the purpose of flat-tail algorithm.  0 means everyone.
	NumLeaders *int `json:"numLeaders,omitempty"`

	// PreTrust Refers to a trust vector.
	PreTrust *TrustVectorRef `json:"preTrust,omitempty"`
}

// ComputeJSONBody defines parameters for Compute.
type ComputeJSONBody struct {
	Alpha   *float64 `json:"alpha,omitempty"`
	Epsilon *float64 `json:"epsilon,omitempty"`

	// FlatTail The length of the flat tail
	// (ranking unchanged from previous iteration)
	// that must be seen before terminating the recursion.
	// 0 means a flat tail need not be seen,
	// and the recursion is terminated solely based upon epsilon.
	FlatTail *int `json:"flatTail,omitempty"`

	// InitialTrust Refers to a trust vector.
	InitialTrust *TrustVectorRef `json:"initialTrust,omitempty"`

	// LocalTrust refers to a local trust.
	LocalTrust LocalTrustRef `json:"localTrust"`

	// MaxIterations The maximum number of iterations after which to stop
	// even if other termination criteria are not met.
	// 0 means no limit.
	MaxIterations *int `json:"maxIterations,omitempty"`

	// NumLeaders The number of top-ranking peers to consider
	// for the purpose of flat-tail algorithm.  0 means everyone.
	NumLeaders *int `json:"numLeaders,omitempty"`

	// PreTrust Refers to a trust vector.
	PreTrust *TrustVectorRef `json:"preTrust,omitempty"`
}

// ComputeWithStatsJSONBody defines parameters for ComputeWithStats.
type ComputeWithStatsJSONBody struct {
	Alpha   *float64 `json:"alpha,omitempty"`
	Epsilon *float64 `json:"epsilon,omitempty"`

	// FlatTail The length of the flat tail
	// (ranking unchanged from previous iteration)
	// that must be seen before terminating the recursion.
	// 0 means a flat tail need not be seen,
	// and the recursion is terminated solely based upon epsilon.
	FlatTail *int `json:"flatTail,omitempty"`

	// InitialTrust Refers to a trust vector.
	InitialTrust *TrustVectorRef `json:"initialTrust,omitempty"`

	// LocalTrust refers to a local trust.
	LocalTrust LocalTrustRef `json:"localTrust"`

	// MaxIterations The maximum number of iterations after which to stop
	// even if other termination criteria are not met.
	// 0 means no limit.
	MaxIterations *int `json:"maxIterations,omitempty"`

	// NumLeaders The number of top-ranking peers to consider
	// for the purpose of flat-tail algorithm.  0 means everyone.
	NumLeaders *int `json:"numLeaders,omitempty"`

	// PreTrust Refers to a trust vector.
	PreTrust *TrustVectorRef `json:"preTrust,omitempty"`
}

// UpdateLocalTrustParams defines parameters for UpdateLocalTrust.
type UpdateLocalTrustParams struct {
	// Merge Controls behavior if a local trust exists under the same ID.
	//
	// If false (default), the local trust ref contents replaces
	// the existing one under the same ID, if any.
	// If true, the local trust ref contents are merged
	// into the existing one under the same ID.
	Merge *bool `form:"merge,omitempty" json:"merge,omitempty"`
}

// ComputeJSONRequestBody defines body for Compute for application/json ContentType.
type ComputeJSONRequestBody ComputeJSONBody

// ComputeWithStatsJSONRequestBody defines body for ComputeWithStats for application/json ContentType.
type ComputeWithStatsJSONRequestBody ComputeWithStatsJSONBody

// UpdateLocalTrustJSONRequestBody defines body for UpdateLocalTrust for application/json ContentType.
type UpdateLocalTrustJSONRequestBody = LocalTrustRef

// AsInlineLocalTrust returns the union data inside the LocalTrustRef as a InlineLocalTrust
func (t LocalTrustRef) AsInlineLocalTrust() (InlineLocalTrust, error) {
	var body InlineLocalTrust
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInlineLocalTrust overwrites any union data inside the LocalTrustRef as the provided InlineLocalTrust
func (t *LocalTrustRef) FromInlineLocalTrust(v InlineLocalTrust) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInlineLocalTrust performs a merge with any union data inside the LocalTrustRef, using the provided InlineLocalTrust
func (t *LocalTrustRef) MergeInlineLocalTrust(v InlineLocalTrust) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStoredLocalTrust returns the union data inside the LocalTrustRef as a StoredLocalTrust
func (t LocalTrustRef) AsStoredLocalTrust() (StoredLocalTrust, error) {
	var body StoredLocalTrust
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStoredLocalTrust overwrites any union data inside the LocalTrustRef as the provided StoredLocalTrust
func (t *LocalTrustRef) FromStoredLocalTrust(v StoredLocalTrust) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStoredLocalTrust performs a merge with any union data inside the LocalTrustRef, using the provided StoredLocalTrust
func (t *LocalTrustRef) MergeStoredLocalTrust(v StoredLocalTrust) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsObjectStorageLocalTrust returns the union data inside the LocalTrustRef as a ObjectStorageLocalTrust
func (t LocalTrustRef) AsObjectStorageLocalTrust() (ObjectStorageLocalTrust, error) {
	var body ObjectStorageLocalTrust
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectStorageLocalTrust overwrites any union data inside the LocalTrustRef as the provided ObjectStorageLocalTrust
func (t *LocalTrustRef) FromObjectStorageLocalTrust(v ObjectStorageLocalTrust) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeObjectStorageLocalTrust performs a merge with any union data inside the LocalTrustRef, using the provided ObjectStorageLocalTrust
func (t *LocalTrustRef) MergeObjectStorageLocalTrust(v ObjectStorageLocalTrust) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LocalTrustRef) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["scheme"], err = json.Marshal(t.Scheme)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'scheme': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *LocalTrustRef) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["scheme"]; found {
		err = json.Unmarshal(raw, &t.Scheme)
		if err != nil {
			return fmt.Errorf("error reading 'scheme': %w", err)
		}
	}

	return err
}

// AsInlineTrustVector returns the union data inside the TrustVectorRef as a InlineTrustVector
func (t TrustVectorRef) AsInlineTrustVector() (InlineTrustVector, error) {
	var body InlineTrustVector
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInlineTrustVector overwrites any union data inside the TrustVectorRef as the provided InlineTrustVector
func (t *TrustVectorRef) FromInlineTrustVector(v InlineTrustVector) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInlineTrustVector performs a merge with any union data inside the TrustVectorRef, using the provided InlineTrustVector
func (t *TrustVectorRef) MergeInlineTrustVector(v InlineTrustVector) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsObjectStorageTrustVector returns the union data inside the TrustVectorRef as a ObjectStorageTrustVector
func (t TrustVectorRef) AsObjectStorageTrustVector() (ObjectStorageTrustVector, error) {
	var body ObjectStorageTrustVector
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectStorageTrustVector overwrites any union data inside the TrustVectorRef as the provided ObjectStorageTrustVector
func (t *TrustVectorRef) FromObjectStorageTrustVector(v ObjectStorageTrustVector) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeObjectStorageTrustVector performs a merge with any union data inside the TrustVectorRef, using the provided ObjectStorageTrustVector
func (t *TrustVectorRef) MergeObjectStorageTrustVector(v ObjectStorageTrustVector) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TrustVectorRef) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["scheme"], err = json.Marshal(t.Scheme)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'scheme': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *TrustVectorRef) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["scheme"]; found {
		err = json.Unmarshal(raw, &t.Scheme)
		if err != nil {
			return fmt.Errorf("error reading 'scheme': %w", err)
		}
	}

	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ComputeWithBody request with any body
	ComputeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Compute(ctx context.Context, body ComputeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ComputeWithStatsWithBody request with any body
	ComputeWithStatsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ComputeWithStats(ctx context.Context, body ComputeWithStatsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteLocalTrust request
	DeleteLocalTrust(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLocalTrust request
	GetLocalTrust(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeadLocalTrust request
	HeadLocalTrust(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateLocalTrustWithBody request with any body
	UpdateLocalTrustWithBody(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateLocalTrust(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, body UpdateLocalTrustJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ComputeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewComputeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Compute(ctx context.Context, body ComputeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewComputeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ComputeWithStatsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewComputeWithStatsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ComputeWithStats(ctx context.Context, body ComputeWithStatsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewComputeWithStatsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteLocalTrust(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteLocalTrustRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLocalTrust(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLocalTrustRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeadLocalTrust(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeadLocalTrustRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateLocalTrustWithBody(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateLocalTrustRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateLocalTrust(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, body UpdateLocalTrustJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateLocalTrustRequest(c.Server, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewComputeRequest calls the generic Compute builder with application/json body
func NewComputeRequest(server string, body ComputeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewComputeRequestWithBody(server, "application/json", bodyReader)
}

// NewComputeRequestWithBody generates requests for Compute with any type of body
func NewComputeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/compute")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewComputeWithStatsRequest calls the generic ComputeWithStats builder with application/json body
func NewComputeWithStatsRequest(server string, body ComputeWithStatsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewComputeWithStatsRequestWithBody(server, "application/json", bodyReader)
}

// NewComputeWithStatsRequestWithBody generates requests for ComputeWithStats with any type of body
func NewComputeWithStatsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/compute-with-stats")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteLocalTrustRequest generates requests for DeleteLocalTrust
func NewDeleteLocalTrustRequest(server string, id LocalTrustIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/local-trust/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLocalTrustRequest generates requests for GetLocalTrust
func NewGetLocalTrustRequest(server string, id LocalTrustIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/local-trust/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHeadLocalTrustRequest generates requests for HeadLocalTrust
func NewHeadLocalTrustRequest(server string, id LocalTrustIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/local-trust/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateLocalTrustRequest calls the generic UpdateLocalTrust builder with application/json body
func NewUpdateLocalTrustRequest(server string, id LocalTrustIdParam, params *UpdateLocalTrustParams, body UpdateLocalTrustJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateLocalTrustRequestWithBody(server, id, params, "application/json", bodyReader)
}

// NewUpdateLocalTrustRequestWithBody generates requests for UpdateLocalTrust with any type of body
func NewUpdateLocalTrustRequestWithBody(server string, id LocalTrustIdParam, params *UpdateLocalTrustParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/local-trust/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Merge != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "merge", runtime.ParamLocationQuery, *params.Merge); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ComputeWithBodyWithResponse request with any body
	ComputeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ComputeResponse, error)

	ComputeWithResponse(ctx context.Context, body ComputeJSONRequestBody, reqEditors ...RequestEditorFn) (*ComputeResponse, error)

	// ComputeWithStatsWithBodyWithResponse request with any body
	ComputeWithStatsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ComputeWithStatsResponse, error)

	ComputeWithStatsWithResponse(ctx context.Context, body ComputeWithStatsJSONRequestBody, reqEditors ...RequestEditorFn) (*ComputeWithStatsResponse, error)

	// DeleteLocalTrustWithResponse request
	DeleteLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*DeleteLocalTrustResponse, error)

	// GetLocalTrustWithResponse request
	GetLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*GetLocalTrustResponse, error)

	// HeadLocalTrustWithResponse request
	HeadLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*HeadLocalTrustResponse, error)

	// UpdateLocalTrustWithBodyWithResponse request with any body
	UpdateLocalTrustWithBodyWithResponse(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateLocalTrustResponse, error)

	UpdateLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, body UpdateLocalTrustJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateLocalTrustResponse, error)
}

type ComputeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TrustVectorRef
	JSON400      *InvalidRequest
}

// Status returns HTTPResponse.Status
func (r ComputeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ComputeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ComputeWithStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ComputeWithStatsResponseOK
	JSON400      *InvalidRequest
}

// Status returns HTTPResponse.Status
func (r ComputeWithStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ComputeWithStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteLocalTrustResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *InvalidRequest
}

// Status returns HTTPResponse.Status
func (r DeleteLocalTrustResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteLocalTrustResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLocalTrustResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InlineLocalTrust
}

// Status returns HTTPResponse.Status
func (r GetLocalTrustResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLocalTrustResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeadLocalTrustResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HeadLocalTrustResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeadLocalTrustResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateLocalTrustResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *InvalidRequest
}

// Status returns HTTPResponse.Status
func (r UpdateLocalTrustResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateLocalTrustResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ComputeWithBodyWithResponse request with arbitrary body returning *ComputeResponse
func (c *ClientWithResponses) ComputeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ComputeResponse, error) {
	rsp, err := c.ComputeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseComputeResponse(rsp)
}

func (c *ClientWithResponses) ComputeWithResponse(ctx context.Context, body ComputeJSONRequestBody, reqEditors ...RequestEditorFn) (*ComputeResponse, error) {
	rsp, err := c.Compute(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseComputeResponse(rsp)
}

// ComputeWithStatsWithBodyWithResponse request with arbitrary body returning *ComputeWithStatsResponse
func (c *ClientWithResponses) ComputeWithStatsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ComputeWithStatsResponse, error) {
	rsp, err := c.ComputeWithStatsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseComputeWithStatsResponse(rsp)
}

func (c *ClientWithResponses) ComputeWithStatsWithResponse(ctx context.Context, body ComputeWithStatsJSONRequestBody, reqEditors ...RequestEditorFn) (*ComputeWithStatsResponse, error) {
	rsp, err := c.ComputeWithStats(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseComputeWithStatsResponse(rsp)
}

// DeleteLocalTrustWithResponse request returning *DeleteLocalTrustResponse
func (c *ClientWithResponses) DeleteLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*DeleteLocalTrustResponse, error) {
	rsp, err := c.DeleteLocalTrust(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteLocalTrustResponse(rsp)
}

// GetLocalTrustWithResponse request returning *GetLocalTrustResponse
func (c *ClientWithResponses) GetLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*GetLocalTrustResponse, error) {
	rsp, err := c.GetLocalTrust(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLocalTrustResponse(rsp)
}

// HeadLocalTrustWithResponse request returning *HeadLocalTrustResponse
func (c *ClientWithResponses) HeadLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, reqEditors ...RequestEditorFn) (*HeadLocalTrustResponse, error) {
	rsp, err := c.HeadLocalTrust(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeadLocalTrustResponse(rsp)
}

// UpdateLocalTrustWithBodyWithResponse request with arbitrary body returning *UpdateLocalTrustResponse
func (c *ClientWithResponses) UpdateLocalTrustWithBodyWithResponse(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateLocalTrustResponse, error) {
	rsp, err := c.UpdateLocalTrustWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateLocalTrustResponse(rsp)
}

func (c *ClientWithResponses) UpdateLocalTrustWithResponse(ctx context.Context, id LocalTrustIdParam, params *UpdateLocalTrustParams, body UpdateLocalTrustJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateLocalTrustResponse, error) {
	rsp, err := c.UpdateLocalTrust(ctx, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateLocalTrustResponse(rsp)
}

// ParseComputeResponse parses an HTTP response from a ComputeWithResponse call
func ParseComputeResponse(rsp *http.Response) (*ComputeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ComputeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TrustVectorRef
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseComputeWithStatsResponse parses an HTTP response from a ComputeWithStatsWithResponse call
func ParseComputeWithStatsResponse(rsp *http.Response) (*ComputeWithStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ComputeWithStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ComputeWithStatsResponseOK
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteLocalTrustResponse parses an HTTP response from a DeleteLocalTrustWithResponse call
func ParseDeleteLocalTrustResponse(rsp *http.Response) (*DeleteLocalTrustResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteLocalTrustResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetLocalTrustResponse parses an HTTP response from a GetLocalTrustWithResponse call
func ParseGetLocalTrustResponse(rsp *http.Response) (*GetLocalTrustResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLocalTrustResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InlineLocalTrust
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHeadLocalTrustResponse parses an HTTP response from a HeadLocalTrustWithResponse call
func ParseHeadLocalTrustResponse(rsp *http.Response) (*HeadLocalTrustResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeadLocalTrustResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpdateLocalTrustResponse parses an HTTP response from a UpdateLocalTrustWithResponse call
func ParseUpdateLocalTrustResponse(rsp *http.Response) (*UpdateLocalTrustResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateLocalTrustResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Compute EigenTrust scores
	// (POST /compute)
	Compute(ctx echo.Context) error
	// Compute EigenTrust scores, with execution statistics
	// (POST /compute-with-stats)
	ComputeWithStats(ctx echo.Context) error
	// Delete local trust
	// (DELETE /local-trust/{id})
	DeleteLocalTrust(ctx echo.Context, id LocalTrustIdParam) error
	// Retrieve local trust
	// (GET /local-trust/{id})
	GetLocalTrust(ctx echo.Context, id LocalTrustIdParam) error
	// Check for existence of local trust
	// (HEAD /local-trust/{id})
	HeadLocalTrust(ctx echo.Context, id LocalTrustIdParam) error
	// Update local trust
	// (PUT /local-trust/{id})
	UpdateLocalTrust(ctx echo.Context, id LocalTrustIdParam, params UpdateLocalTrustParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Compute converts echo context to params.
func (w *ServerInterfaceWrapper) Compute(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Compute(ctx)
	return err
}

// ComputeWithStats converts echo context to params.
func (w *ServerInterfaceWrapper) ComputeWithStats(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ComputeWithStats(ctx)
	return err
}

// DeleteLocalTrust converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLocalTrust(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id LocalTrustIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteLocalTrust(ctx, id)
	return err
}

// GetLocalTrust converts echo context to params.
func (w *ServerInterfaceWrapper) GetLocalTrust(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id LocalTrustIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLocalTrust(ctx, id)
	return err
}

// HeadLocalTrust converts echo context to params.
func (w *ServerInterfaceWrapper) HeadLocalTrust(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id LocalTrustIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HeadLocalTrust(ctx, id)
	return err
}

// UpdateLocalTrust converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateLocalTrust(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id LocalTrustIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateLocalTrustParams
	// ------------- Optional query parameter "merge" -------------

	err = runtime.BindQueryParameter("form", true, false, "merge", ctx.QueryParams(), &params.Merge)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter merge: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateLocalTrust(ctx, id, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/compute", wrapper.Compute)
	router.POST(baseURL+"/compute-with-stats", wrapper.ComputeWithStats)
	router.DELETE(baseURL+"/local-trust/:id", wrapper.DeleteLocalTrust)
	router.GET(baseURL+"/local-trust/:id", wrapper.GetLocalTrust)
	router.HEAD(baseURL+"/local-trust/:id", wrapper.HeadLocalTrust)
	router.PUT(baseURL+"/local-trust/:id", wrapper.UpdateLocalTrust)

}

type ComputeWithStatsResponseOKJSONResponse struct {
	// EigenTrust Refers to a trust vector.
	EigenTrust TrustVectorRef `json:"eigenTrust"`

	// FlatTailStats Flat-tail algorithm stats and peer ranking.
	FlatTailStats FlatTailStats `json:"flatTailStats"`
}

type InvalidRequestJSONResponse struct {
	// Message Describes the error in a human-readable message.
	//
	// It may be empty.
	Message string `json:"message"`
}

type ComputeRequestObject struct {
	Body *ComputeJSONRequestBody
}

type ComputeResponseObject interface {
	VisitComputeResponse(w http.ResponseWriter) error
}

type Compute200JSONResponse TrustVectorRef

func (response Compute200JSONResponse) VisitComputeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.union)
}

type Compute400JSONResponse struct{ InvalidRequestJSONResponse }

func (response Compute400JSONResponse) VisitComputeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ComputeWithStatsRequestObject struct {
	Body *ComputeWithStatsJSONRequestBody
}

type ComputeWithStatsResponseObject interface {
	VisitComputeWithStatsResponse(w http.ResponseWriter) error
}

type ComputeWithStats200JSONResponse struct {
	ComputeWithStatsResponseOKJSONResponse
}

func (response ComputeWithStats200JSONResponse) VisitComputeWithStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ComputeWithStats400JSONResponse struct{ InvalidRequestJSONResponse }

func (response ComputeWithStats400JSONResponse) VisitComputeWithStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteLocalTrustRequestObject struct {
	Id LocalTrustIdParam `json:"id"`
}

type DeleteLocalTrustResponseObject interface {
	VisitDeleteLocalTrustResponse(w http.ResponseWriter) error
}

type DeleteLocalTrust204Response struct {
}

func (response DeleteLocalTrust204Response) VisitDeleteLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteLocalTrust400JSONResponse struct{ InvalidRequestJSONResponse }

func (response DeleteLocalTrust400JSONResponse) VisitDeleteLocalTrustResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteLocalTrust404Response struct {
}

func (response DeleteLocalTrust404Response) VisitDeleteLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLocalTrustRequestObject struct {
	Id LocalTrustIdParam `json:"id"`
}

type GetLocalTrustResponseObject interface {
	VisitGetLocalTrustResponse(w http.ResponseWriter) error
}

type GetLocalTrust200JSONResponse InlineLocalTrust

func (response GetLocalTrust200JSONResponse) VisitGetLocalTrustResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLocalTrust404Response struct {
}

func (response GetLocalTrust404Response) VisitGetLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type HeadLocalTrustRequestObject struct {
	Id LocalTrustIdParam `json:"id"`
}

type HeadLocalTrustResponseObject interface {
	VisitHeadLocalTrustResponse(w http.ResponseWriter) error
}

type HeadLocalTrust204Response struct {
}

func (response HeadLocalTrust204Response) VisitHeadLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HeadLocalTrust404Response struct {
}

func (response HeadLocalTrust404Response) VisitHeadLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateLocalTrustRequestObject struct {
	Id     LocalTrustIdParam `json:"id"`
	Params UpdateLocalTrustParams
	Body   *UpdateLocalTrustJSONRequestBody
}

type UpdateLocalTrustResponseObject interface {
	VisitUpdateLocalTrustResponse(w http.ResponseWriter) error
}

type UpdateLocalTrust200Response struct {
}

func (response UpdateLocalTrust200Response) VisitUpdateLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateLocalTrust201Response struct {
}

func (response UpdateLocalTrust201Response) VisitUpdateLocalTrustResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type UpdateLocalTrust400JSONResponse struct{ InvalidRequestJSONResponse }

func (response UpdateLocalTrust400JSONResponse) VisitUpdateLocalTrustResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Compute EigenTrust scores
	// (POST /compute)
	Compute(ctx context.Context, request ComputeRequestObject) (ComputeResponseObject, error)
	// Compute EigenTrust scores, with execution statistics
	// (POST /compute-with-stats)
	ComputeWithStats(ctx context.Context, request ComputeWithStatsRequestObject) (ComputeWithStatsResponseObject, error)
	// Delete local trust
	// (DELETE /local-trust/{id})
	DeleteLocalTrust(ctx context.Context, request DeleteLocalTrustRequestObject) (DeleteLocalTrustResponseObject, error)
	// Retrieve local trust
	// (GET /local-trust/{id})
	GetLocalTrust(ctx context.Context, request GetLocalTrustRequestObject) (GetLocalTrustResponseObject, error)
	// Check for existence of local trust
	// (HEAD /local-trust/{id})
	HeadLocalTrust(ctx context.Context, request HeadLocalTrustRequestObject) (HeadLocalTrustResponseObject, error)
	// Update local trust
	// (PUT /local-trust/{id})
	UpdateLocalTrust(ctx context.Context, request UpdateLocalTrustRequestObject) (UpdateLocalTrustResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Compute operation middleware
func (sh *strictHandler) Compute(ctx echo.Context) error {
	var request ComputeRequestObject

	var body ComputeJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Compute(ctx.Request().Context(), request.(ComputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Compute")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ComputeResponseObject); ok {
		return validResponse.VisitComputeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ComputeWithStats operation middleware
func (sh *strictHandler) ComputeWithStats(ctx echo.Context) error {
	var request ComputeWithStatsRequestObject

	var body ComputeWithStatsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ComputeWithStats(ctx.Request().Context(), request.(ComputeWithStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ComputeWithStats")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ComputeWithStatsResponseObject); ok {
		return validResponse.VisitComputeWithStatsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteLocalTrust operation middleware
func (sh *strictHandler) DeleteLocalTrust(ctx echo.Context, id LocalTrustIdParam) error {
	var request DeleteLocalTrustRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLocalTrust(ctx.Request().Context(), request.(DeleteLocalTrustRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLocalTrust")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteLocalTrustResponseObject); ok {
		return validResponse.VisitDeleteLocalTrustResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLocalTrust operation middleware
func (sh *strictHandler) GetLocalTrust(ctx echo.Context, id LocalTrustIdParam) error {
	var request GetLocalTrustRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLocalTrust(ctx.Request().Context(), request.(GetLocalTrustRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLocalTrust")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLocalTrustResponseObject); ok {
		return validResponse.VisitGetLocalTrustResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// HeadLocalTrust operation middleware
func (sh *strictHandler) HeadLocalTrust(ctx echo.Context, id LocalTrustIdParam) error {
	var request HeadLocalTrustRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HeadLocalTrust(ctx.Request().Context(), request.(HeadLocalTrustRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadLocalTrust")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HeadLocalTrustResponseObject); ok {
		return validResponse.VisitHeadLocalTrustResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateLocalTrust operation middleware
func (sh *strictHandler) UpdateLocalTrust(ctx echo.Context, id LocalTrustIdParam, params UpdateLocalTrustParams) error {
	var request UpdateLocalTrustRequestObject

	request.Id = id
	request.Params = params

	var body UpdateLocalTrustJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateLocalTrust(ctx.Request().Context(), request.(UpdateLocalTrustRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateLocalTrust")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateLocalTrustResponseObject); ok {
		return validResponse.VisitUpdateLocalTrustResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x83XLbuJL/q6Do/7+OvUvr044TTZ2LTJzZdZ3smVScmXMxSpUgsikiIQEGAGV7Uq7K",
	"O5zb3dt9sDzJVjdAipQoWcrYW3OxuYlM4aPR/etPNPUliFReKAnSmmDyJSi45jlY0PTXGxXx7L0ujb2K",
	"3+I3+DAGE2lRWKFkMAlmIp6xGKSyYJhNgWU4h1mcxCKVZRDhSCYk+1yCwc+9qQzCQODsgts0CAPJcwgm",
	"gYiDMNDwuRQa4mBidQlhYKIUco4b/z8NSTAJjvorkvvuW9NvUhrch4Ep85zru2DizuDpuboM7u/dFmDs",
	"jyoWQOd8pfKitPCufn6HTyMlLUiLH3lRZCLiSH3/o8GDfwngludF5hb4D2GMkIsVFZuMupLMpsIwPy1s",
	"MWp+x45GTBiWu4X6pfwk1Q2y6i1o9losQNK6jGcLpYVN83AqhcUp3Jgyh5hZxeZAIjA8B8adOAoNp7RH",
	"byrfpxxnhH6vxkRHxdGAcRmzo2E4lfREyAU7GrJElZpZkQPOYXkZpfj/0cAJcsXql2x8WgDo6ozsRti0",
	"OtL6eTnDoUEYLHlWAjE5K1IeTAa9YRhkLU6CtJpE9duXQASTQRh8DCbDMFgGk+F92Hg2omdj/2zYeDa8",
	"/+CxREiTmZCAxIvfgSYEhYYd+zV2cvue7V4PYbYBipcyftvY5QF8SGXZRxLL6C+mzb0ScWAUCngqawk3",
	"8LMbN5yVUiRK56w1tzQQM5EwqdrPTQGRSATECIsKQig8xMC3r/88GjGuG0iDmMHnkmfZHWEOSPltqWVI",
	"iNyCh6PRVO6PZkR/D3rbkAxL0HdKQoOQ70QqKkS9658FrYiua4GEDzeB9L6BIlZwY1BtW2dSCRt7AR57",
	"CZ6E7CYFDZOpnMpTtAQ01DhjQA8c4vzTEfv29Z/M3ogIWjbBjx6uBobIQno4qh8OQkbS0xCJQquIo/M4",
	"GvzFsMpUTWVtjNbB9YMXulQ48GiIn5vYa1irXGnEEJfOWE3l2xrXxmqQC5uy4xlJcnaC6wx6Qxp3ZUGT",
	"tWc21WBSlcXseAaFEZmSbiifG5D2B1QJkA6ooJegUY2Q4TEkvMwsI8BM5ZyjdpWFcmNlmc9BoyS8HMYn",
	"6xh1Al4D6h9G4KA3Ou8A4aB3cd6JQ/dsRM8Gj2RJB71Ry5YOes/3xfvoAbwL02UzlkKVDcsKtxEU1kP9",
	"V2SnIZCZiGcQs1gkCWiQNrv7AUd0gYGEsA6JhViCZHCLsYKwZHUaThdpcdjLYAmZQaNX00oyPj4akKnE",
	"A0XcwMlUxor8QMqX4E0iQt0TqjSLuFRSRDwTv0NcrRhlwkFTyYyeCM00ZNyKJbCcL6SwZYyfLAZ6nkqo",
	"CWdi88BTWZ/1r0M4HQ5mIW4/6A2qf8MTst9kCRIhQTvFoxOK3+HUKYDXClxuCKfPWJ+NWyuNv33975Nw",
	"Ko1iwrIbkWXM8k/gNLmmy6zW3pDuVKJ7pJkaDGqgkG46j6JScwtMc/lJyEU4lUC+DT0E47ki038D+hQH",
	"QOxVUwLXTnhcZM46tF01ajFxujKqNlXlIg2nco1liJEYEiGFBdxRMrUE/Ulk2cRJoBaSp9AT1fa1dDQE",
	"RZRyuYCp5IlFU4IUcJbATYNPRO4lwk0VuAaiHGSkSs0Xzl/CbQFa5CDtVKK9taUEVsOaPCrhRwLEBjnW",
	"W/QwSKigxawqaNMoQz7dCCmrjXAKBQ2cRYprgwjPuF6APmnsQMfJxCfkiCmTRESwlyV0Lvu4lBIiMIZr",
	"kd2dEPKYX3ubray+npBUnsR7P4XVPDD+vG+mToVG+Vuf7nhmoCElbUS+nIcBRoTcBpMgVuWcXE3Ob0Ve",
	"5rRnLqT7PAgDe1fgrs6JYbpVs/TLH1klybh9z0XWZeOBZc5fq4Rgh2NJI6fyuNKWUjqViFmiVb4yDbU+",
	"nPgANqeYEz02SDaHhMIE0LmQnHIeS7oYldq4dHXAcuASvXq9LaGb1NCvE3r9aU4ld+TXhZgZlSHKG6GA",
	"55sDfAdvhLSwcMxBqyEaON2VDdOgXyGySr+DBGe3Mb5fJu2n5vy29oCmWzRewo2opmGqnXm6SUWUojkx",
	"VhVTCegp0YzYFD1FxXslWaRxruDOhCjLcrANEUjFMpELuw/LZJm/AR77YsYm2StyrSpOKxR5G65YpKQR",
	"MeipTJTzAEWpC2XI4CMQTgkIdWbVY6yisso/9qGyqfiHCPW+WSv5rSnhD/U2av4RIhuQNWif/21d6GF4",
	"OjTRVANhvjjiKG8XY9yWplDStOom/xA2vbbcmnf+y5//tkf9ZJt1gjppPRzmlQUhah6a/lNr8Do/G2Ss",
	"r7sPf6/LCN1SUmJs4XnrrEMjKTeR0rAKwCresrmKcZK0XEgXxNYruCkY295AluH/S67Ryk2lsdwKY0Vk",
	"KHPyeDbsOOfyzsUWPkf29nMNv5SB3IfBlVzyTMS+GnZgJey1+9yRl75kdXGR0QZO30FrpR3aam+do0Nf",
	"IIMjLtEGZIrHzRR2wnyBrJXXakgYCWan96sXXyfwkv6a+zom0YWxI2dpmXN5qoHHfJ4B8wv4RJHl/A59",
	"AOSF9XUGDw5jtZCLDWBV+++DolcUyTPMNDFcFE4yTR1dnZQO99O6ArTX+2lT6gxh4xBD4ZWHTS8I1/gW",
	"Q2b535XOu41plRNxU7noFHhcfc64sSvMUV2Ikhx0v67wZBUFb6cUgHq/6P3EDWbYCIOSyjNdppf43hF6",
	"7Ao3XEDRfZrVHj7sODb8LmRvKI2TlPS7M73512HT2aU8XiV1npUn1XF9ctrpJSkuiVSZxRRQ8CXEUzm/",
	"237kqTwuuKm/RaG7alel4atkFSXM5pCpm5OpvElFhrlQKmBZxTqOWsqW9vFY/lzdnDNKo5mpvKmvcDAh",
	"YxGRrXvrsiplWaJKGbMUNLgE93fQii0yNa802t8UWMid5u6kyj/hWvM7+rs6/xY6y8UCqGDkl20wbGWo",
	"jiveohCvrMvgXLhShZkJz0wjHjVMzakSFPem0lvDCbtKGK95UlDiLdnLH19dXr5+/fr1T/U/dsNXC0zl",
	"MfAoZRngeCo6sRgtvIxsDa4qfvUqQwtonEap11zZlF1eknrjThRVrVM8lSqpcD6koWPyRRBhMkp1jKtG",
	"WSJk7ytO/fWMCsQ1K4VkSscY0SkmFlJpIFUxm3s+jLP1+MZpa1OuYcMmrVC5aVfRpWF+tOt65h0kPuxr",
	"10pzbrW4ZVOfYk0DXwEw1lu3QglJScOxBiobRSQVXEgyuEVBU33BWKWh5cTcDU7ENeZ63suTn60t6CYh",
	"U4lpr5A+z3AbAnMnZcIayBLH2rWgqsoo18/9qhllSCVPSQn9cOY32qTDxSxUcdV9V3kFVnCh6ysIp9cI",
	"N7RSC1QXWjoWGkltVfGlqj145uxhKoo15d8Vya2L97W0+q7LJlQJ82ZskohbjK7IZbPZStwzRwZIROlv",
	"VaL9YcPJV6n3ZlCxuhpdL/pucrdiiLCGmc8lci8WOUgjNpLE4YMa4w/rKQtrDOyjII6DHVpSaDAEUUQ3",
	"DnoAI6vzc8uUrCqdMzE7YUXGI1crb2CCQi7p8kI/9uPshHwhr66iIsZzVUrLjmfLmS+cr4LQrqL3+bZL",
	"lraaiN0CrC9FkbAq/iOzjND2JU4hY7j11YCq0JCBMe16KDuuBXtC9pdiThllauMKqubmg4754x7k+7rm",
	"n5D65U684Q7HhTICfdJJBQDcGreZSgITlcAJNTMxQyS5zx9n3xEgrmmTCJC/SOV2/WkkpLs9jGPNkkY+",
	"nm9prvqwc2mO3t+ttNRsy+3O+ar+uUfls7nMjpHnm9r6x5xa8/zucpCM8gPuaw13BzupBkQe00shJlwX",
	"jssT8fFKkE/vw1rQY7UPc0Hb/4Ln2mDrY7uuSmeFYd7SUGlg5c2+y0O1Lwu88hzqlf6YOW+X1Vc2fE09",
	"ntR6N1haGe/HMdjdxrrVLLaVtXxLK1vNjDe+fjDsUKR2FZ3uXLKfE5J8W7bbdP1Nu67lDbIbHTL+CaGr",
	"2C/vrvyzThUPA+cZgtCfHv+sak/CZvDARr0Hi1me/A8IYiXBH/GQWD3AqbsmXNMRDpjwMx312h21Oe8D",
	"qlabzbo77dvL1+28Fxx2BZyDwWP5Qlw8DibBOGiM8sKuvwS54AvIQdquUV2asY11h6bLZBs15OiPfBDh",
	"oUddMvUdb4vDNYVtrIZBqTOkezzp9+dl9AnsqeQ59Atu075V/URk0IvMMti0nPt70taeG2nfpvasKzzR",
	"uL7NL+/etKMtzx6iuCof14rnuPnq+lf6PnQX3DbVgLFbVubSoGEMMZylpio2WyKZr0rtmlVonxmxacZw",
	"a3d6dvzyH9fsenziSjVFQQW6fSrVtRvGwz0Il+8Lfv8PKd1I8ew5BCk3qomTPwdCNoz33pbE5zSq2VtH",
	"nLjeKKQh2SIGaalL1XEDo8+rSy+2roqYiA/uKd8bIo72DWx4y/thb66KuJOpa/ee3xFdvG9i7EnDi507",
	"PV180TRGB8ULrYkdAcM2Q9bSluaFnpCJIlHU7Uzv25fAP3IjIvby7RWjNqe8jpfdF1093MQ3z+CulTDy",
	"BepACSbBoDfsDRA2qgDJC4FRQ2/Qw8gB7SLhpO/vl+m2VHWpqb/q37y99jdUSLDrfxSyKK271H653lVA",
	"zXzGtei6cdSFydi/sDcbUUSIzsEUXBtgmAi4casW3jrb3DmqavQNqXtHUYPPKRVWqlx2DvYGQDLXcDx0",
	"C7ym69/6ruGA2e4uvysoMqyC9g+MZ5lrfnG9cor4zDMHI1RhqoNjflKxPmi+uHK3zXi13m3pd7zYst7D",
	"MRoMDrzi39157i85614Gfxv57et/drbxffv6X43rbFeE8Q3eOM31EzqTnopFShhy0udZCSHDdBWyu6lM",
	"VJapm0YF8GjwA3Pd4S7N5dXUyrUd0Gq9pdB1NhiPRy/Gw/HFi7PRxcV6V/PwYnBx9mI4Ph9cXJyPLy7W",
	"Mv2z0fmL0fD8fDgcPR8+Pz9/oKPvoRboAxnvSn47GygbsmF8rpYuEvk7hmpUE2lEK6smamq1VdpVGZxX",
	"Jk1Q7tJ8sxubyFjVJKgRePj/6y7sCMKpjCFX0li9as+j3s3WpWejnfYJGkh3I+DZi+fDwejs2fhZNwQG",
	"z4cvnp+9eD561o2B0fDFi+Ho/NnDbfD7vQ630Sv2BP1Jq9R5bVbtEAmW3vX7Vg/fHSAkQ3JAxtQjQFfG",
	"Kqm76pezE2oB57S8mltOaYIvUvgGFdesdObMV7cp9Gauv9bRdN96QXCrZ6NxlWc8RbScmqqt5hGd5DUA",
	"q3ahXrwYqhtyZDo1Wq+Uwak5t6vXwzplVr8jtr0tDJVVgy21rAxip9upm/ue1v/sFuCORsOnxYA3T3AL",
	"UUntaituOniQn3ehRv+LiO99pxS4WKrN0Ut63kiGwtb7tlsC29WQ/ub7uGgw1th5tqV9uhGQoLl0RMbM",
	"NAxB77u5idP22DhW4Fp/4FYY21uTguNPcwIuvIDOrBGB21AomtTZZsGcb1jdiXSB/d/APrVcBgf1xB5W",
	"QiUD/wgSeAfo5ZYbMkiBx1uFMBqcMZGsy6J6ExO3MSE7G5y5ePdGGOiSwL8Dj/8EquHo7T0Sol+lEH0i",
	"o05fu0vVZJ27RWm7LgB4TAa7QnbEoxTW76umknrQunm/dv/X5vcvRcwf2xiFXRexWmWGzSHlS6E0AoV3",
	"MJyVktrGqmbEq0tX9Up849ixf1XlJNy4sdOQrO62NbimEhds0toUYUjY3CEkYiS1t9FFFDywOIW3oBcQ",
	"T6WQPvDZvUfjtw4+l6DvVj92QAsFzYDOFw/mSmXAZXDvAHzITxIc+lsJW2LDl5td1YpasHuMvXJxXNcl",
	"8+b7At028GHfVBI2O3zTaDDcb4VIA38879bSaac4bR2mEVSidKqzSeDLt1fVC8Kpoi6c+R37G9c5H7M3",
	"fO77IV39OrW2MJN+nxei92mc9YTqz7kRUX857HcoGXWzQpac+oUdZW6zkOlS4lYzep/Bl0Twq9n6jpO+",
	"C2ZwlcnzwfNBvWlw/+H+fwIAAP//2xdwQilEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
